name: Push to Lambda

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Deploy to Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Install QEMU
        uses: docker/setup-qemu-action@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::558072131675:role/ECR-CodeDeploy
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Docker Build
        uses: docker/build-push-action@v5
        env:
          REGISTRY:
          REPOSITORY: my-ecr-repo
          IMAGE_TAG: ${{ github.sha }}
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.login-ecr.outputs.registry }}/n9o6u1y0/smartmatrix:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
